apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-deployment
spec:
  selector:
    matchLabels:
      app: tcp-server
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
      - name: tcp-server
        image: ipv6applicationimage.azurecr.cn/tcp-server:0.0.1-snapshot
        ports:
        - containerPort: 8888